[package]
name = "neotron-api"
version = "0.1.0"
edition = "2021"
authors = [
    "Jonathan 'theJPster' Pallant <github@thejpster.org.uk>",
    "The Neotron Developers"
]
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
neotron-ffi = "0.1"
bitflags = "2"
